
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Nirav Kakkad  ## put your name
title: 'Data Engineer'  ## your title
location: Gandhinagar, Gujarat, India


## Social Profiles
facebook: https://www.facebook.com/nirav.kakkad.9  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
